[params]
  #CODE für den Online Service, der bei Registrierung zum Tracking angegeben wurde (leer = deaktiviert, auch leer für self-hosted!)
  GoatCounter_ID = ""
  #
  # nur bei self-hosted die folgenden Werte setzen (sonst leer lassen!)
  # es ist möglich nur GountCounter_SRC zu setzten, wenn das count.js selbst gehostet wird.
  #URL des Endpoints wo das Script /count aufruft (bsp: "https://count.example.com", /count wird immer angehängt!)
  GoatCounter_URL = ""
  #Source für das Script Tag von dem count.js geladen wird (ohne http/https, mit Dateiname, bsp: "count.example.com/count.js", default = GoatCount_URL, /count.js wird immer angehängt!)
  GoatCounter_SRC = ""
